name: Andrew Doering CV & Blog
firstname: Andrew
lastname: Doering
url: http://127.0.0.1:4000
social:
  facebook:
    - url: https://www.facebook.com
    - user: and.doe
    - icon: fa fb-icon
  github:
    - url: https://www.github.com
    - user: delize
    - icon: fa github-icon
  linkedin:
    - url: https://www.linkedin.com/in
    - user: andrewdoering
    - icon: fa linkedin-icon
  